### ISSUE TITLE
List concatenation

### ISSUE THREAD

**Issue by protz** [CatalaLang/catala#109]
The `@` operator is missing for list concatenation... this would be helpful for combining results from multiple sub-scopes, wherein the sub-scopes can return a list of, say, penalties

**Comment by denismerigoux** [comment]
We should indeed add this. Not sure if `@` is the right syntax though, let's ask the lawyers what they think.

**Comment by EmileRolley** [comment]
> We should indeed add this. Not sure if `@` is the right syntax though, let's ask the lawyers what they think.

Any feedback from the lawyers about the desired syntax?

**Comment by denismerigoux** [comment]
Not yet, you can try and ask Liane or Lilya on the french law Zulip channel.

**Comment by denismerigoux** [comment]
Closed by #137
