### ISSUE TITLE
Feature: staged variable re-definitions

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#114]
## The problem

While the default logic foundation of Catala accurately captures the base case/exceptions structure of statutes' drafting style, there is one pattern which is uneasily capture by the current form of the language. Let us suppose the following statute:

```
### Article 1

Variable X is equal to the capital gain income.

### Article 2

If the taxpayer has no capital gain income, then variable X is equal to the non-capital gain income.

### Article 3

Variable X is capped at $50,000
```

Those three articles all define the same variable, `X`. However, the first two really are a piecewise definition that can be captured by the existing mechanisms of Catala:

~~~
### Article 1

Variable X is equal to the capital gain income.

```catala
scope Foo:
  label base_X
  definition X equals to capital_gain_income
```

### Article 2

If the taxpayer has no capital gain income, then variable X is equal to the non-capital gain income.

```catala
scope Foo:
  exception base_X
  definition X under condition not (has_capital_gain_income) consequence equals to other_income
```
~~~

However, the last article has a different semantic meaning. Indeed, it is meant as a _redefinition_ or _replacement_ for variable X, that depends on the previous value that this variable had.

The way we would solve it now in Catala would be by introducing a new context variable `X_capped` and saying;

~~~
### Article 3
Variable X is capped at $50,000

```catala
scope Foo:
  definition X_capped equals to if X >=$ $50,000 then $50,000 else X
```
~~~

### The proposal

While defining `X_capped` is perfectly fine from a computational point of view, lawyers (Sarah and Liane) don't feel it is right. Moreover, this pattern has appeared several times in our examples, whether US (Section 121) or French (Allocations familiales). In the allocations familiales examples, there is even 3 or 4 layers of re-definition for a single variable. Hence, we should have syntactic and semantic support for this pattern. 

In this proposal, we can rewrite the whole thing as follows:

~~~
### Article 1

Variable X is equal to the capital gain income.

```catala
scope Foo:
  label base_X
  state uncapped
  definition X equals to capital_gain_income
```

### Article 2

If the taxpayer has no capital gain income, then variable X is equal to the non-capital gain income.

```catala
scope Foo:
  exception base_X
  state uncapped
  definition X under condition not (has_capital_gain_income) consequence equals to other_income
```

### Article 3
Variable X is capped at $50,000

```catala
scope Foo:
  state capped replaces uncapped
  definition X equals to if X >=$ $50,000 then $50,000 else X
```
~~~

French version of the keywords : `remplace` and `état`. Basically, we need to tag all the definitions of `X` with the `state` that they belong to, and then declare data flow relations between the states. Here, the definition of article 3 overwrites the definition at article 1 and 2.

### Semantics

The advantage of this proposal is that it can be viewed as a pure syntactic sugar that gets eliminated when compiling to the scope language. Indeed, during the definition grouping phase to build the default tree for a variable, we would instead group 
definitions for each variable by state, and build one default tree by state. Name resolution of the self references can be done thanks to the declared relations between states.

### Implementation

This proposal will affect the `surface/parser.mly` with the new keywords, as well as `surface/ast.ml`.  `surface/name_resolution.ml` and `surface/desugaring.ml` should be almost untouched. The bulk of the work will lie in `desugared/desugared_to_scope.ml`, where the self references will have to be resolved thanks to the state connections and the multiple default trees built for each surface variable (yielding multiple different scope languages variables).

**Comment by msprotz** [comment]
Note from discussion with @denismerigoux: the `stage uncapped` underneath `exception base_X` is superfluous because at desugaring time, it suffices to lookup label `base_X` to realize that `base_X` is associated to stage `uncapped`.

To be determined at implementation-time whether this annotation will no longer be required, or whether it'll be required with a consistency check (for readability).

**Comment by denismerigoux** [comment]
The feature was approved by Sarah and Liane today, so we can go ahead and implement it!

**Comment by EmileRolley** [comment]
II don't really understand the use of labels. Is it used to explicitly link a variable to its definitions but can be omitted?

**Comment by denismerigoux** [comment]
What kind of label are you referring to ? exception-related `label` or re-definition related `state` ?

**Comment by EmileRolley** [comment]
> What kind of label are you referring to ? exception-related `label` or re-definition related `state` ?

The first one.

**Comment by denismerigoux** [comment]
Labeling a particular definition of a variable is useful to define exceptions, see https://catala-lang.org/en/examples/tutorial#tutorial_en.catala_en-359. When you define an exception, you need to know which is the base case of the exception. You can omit the label and just put `exception` when that base case is unambiguous, e.g. there are two definitions, one has `exception` hence the other must be the base case.
