### ISSUE TITLE
Feature: annotate exceptions with location information

### ISSUE THREAD

**Issue by msprotz** [CatalaLang/catala#115]
Working with the JS backend, I get this sort of exceptions:

```
1: Object { t: 9, c: "Runtime.NoValueProvided", l: 23 }
```

if there was a way to annotate the `NoValueProvided` with a location, or better, the actual variable for which no value was provided, it'd be really great!

**Comment by denismerigoux** [comment]
Thanks Jonathan for raising this ! To give `NoValueProvided` a location, the relevant places in the code to change are 

https://github.com/CatalaLang/catala/blob/8ab73627935583495603933f68d43ac6c3f10e0e/src/catala/lcalc/to_ocaml.ml#L229

https://github.com/CatalaLang/catala/blob/8ab73627935583495603933f68d43ac6c3f10e0e/src/catala/runtime.mli#L39

The position should be embedded in the generated code with 

https://github.com/CatalaLang/catala/blob/8ab73627935583495603933f68d43ac6c3f10e0e/src/catala/runtime.mli#L76-L83

in the manner of

https://github.com/CatalaLang/catala/blob/8ab73627935583495603933f68d43ac6c3f10e0e/src/catala/lcalc/to_ocaml.ml#L332-L337

**Comment by EmileRolley** [comment]
Could you give me an example of workflow to get this exception please? @msprotz

**Comment by denismerigoux** [comment]
Fixed by #132
