### ISSUE TITLE
Extra catala markers in the website examples

### ISSUE THREAD

**Issue by msprotz** [CatalaLang/catala#118]
The website still features "```catala" in the rendered HTML... I think it should be trimmed. Maybe a side effect of the recent switch to markdown syntax?

**Comment by denismerigoux** [comment]
Yes indeed. I tought about trimming it but it's complicated because we need to include them for `pygmentize` to work correctly, hence they need to be here until the HTML is generated. However, the HTML generated by `pygmentize` has a structure that make it complex to remove one line with simple regexes : https://gist.github.com/denismerigoux/270966ec26333bc4fd0279e451cfed7b

**Comment by EmileRolley** [comment]
Is it enough to remove markers here?

https://github.com/CatalaLang/catala/blob/144cca12a6346b25be06e0fdcc5d707064cf9300/src/catala/literate/html.ml#L120-L122

**Comment by denismerigoux** [comment]
Yes this is exactly the place where they should be removed.

**Comment by denismerigoux** [comment]
The issue is actually not fixed:
![Capture du 2021-06-04 17-07-35](https://user-images.githubusercontent.com/1766128/120823174-73c44000-c557-11eb-9515-a63bac69082d.png)

As you can see there's now a off-by-a-half error on the line number and the corresponding line of code, I think you need to remove more things @EmileRolley with the regex.

**Comment by EmileRolley** [comment]
> The issue is actually not fixed:
> ![Capture du 2021-06-04 17-07-35](https://user-images.githubusercontent.com/1766128/120823174-73c44000-c557-11eb-9515-a63bac69082d.png)
> 
> As you can see there's now a off-by-a-half error on the line number and the corresponding line of code, I think you need to remove more things @EmileRolley with the regex.

Indeed... How did you apply style?

**Comment by denismerigoux** [comment]
It's there : https://github.com/CatalaLang/catala-website/blob/master/assets/catala_code.css. The workflow I use is that I run in the Catala repo:

    make website-assets -B
    ./generate_website_assets.sh ../catala-website/assets
   
You need to have cloned https://github.com/CatalaLang/catala-website before. Then you follow the instruction on the website readme to fire up the site locally and you navigate the website to see how it's rendered.

**Comment by EmileRolley** [comment]
I'm having hard time to run the server.. I didn't find how to solve this error:
```
catala-website [master●] npm run server                     

> catala-website@1.0.0 server
> webpack serve

[webpack-cli] Error: Plugin could not be registered at 'html-webpack-plugin-before-html-processing'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.
    at Compilation.plugin (/home/emile/Projects/catala-website/node_modules/tapable/lib/Tapable.js:69:9)
    at Compilation.deprecated [as plugin] (node:internal/util:104:12)
    at /home/emile/Projects/catala-website/node_modules/favicons-webpack-plugin/index.js:57:19
    at SyncHook.eval [as call] (eval at create (/home/emile/Projects/catala-website/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/home/emile/Projects/catala-website/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/home/emile/Projects/catala-website/node_modules/webpack/lib/Compiler.js:631:26)
    at /home/emile/Projects/catala-website/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/emile/Projects/catala-website/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/emile/Projects/catala-website/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/home/emile/Projects/catala-website/node_modules/webpack/lib/Compiler.js:662:28)
    at /home/emile/Projects/catala-website/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/emile/Projects/catala-website/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/home/emile/Projects/catala-website/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/home/emile/Projects/catala-website/node_modules/webpack/lib/Watching.js:41:32)
    at /home/emile/Projects/catala-website/node_modules/webpack/lib/Watching.js:33:9
    at Compiler.readRecords (/home/emile/Projects/catala-website/node_modules/webpack/lib/Compiler.js:529:11)
```

Do you have any idea how to solve this? @denismerigoux

**Comment by denismerigoux** [comment]
Did you follow exactly the instructions on the website repo Readme? If yes, it's the first time I see this error, don't know what it is.

**Comment by EmileRolley** [comment]
Okey, so I solved this error but now, a new one appears when the server is launched:
```
ERROR in ./src/Playground.bs.js
Module not found: Error: Can't resolve '../ace-editor/src-min-noconflict/ace.js' in '/home/emile/Projects/catala-website/src'
 @ ./src/Playground.bs.js 10:2-52
 @ ./src/Router.bs.js
 @ ./src/Index.bs.js

ERROR in ./src/Playground.bs.js
Module not found: Error: Can't resolve '../ace-editor/src-min-noconflict/theme-monokai.js' in '/home/emile/Projects/catala-website/src'
 @ ./src/Playground.bs.js 12:2-62
 @ ./src/Router.bs.js
 @ ./src/Index.bs.js
```

**Comment by denismerigoux** [comment]
Try `git submodule update --init`. This should be added in the website's repo instruction.

**Comment by denismerigoux** [comment]
It initializes the git submodule repository for the Ace online editor, which is needed for the playground section of the website.

**Comment by EmileRolley** [comment]
Ok this worked! Thank you!

**Comment by EmileRolley** [comment]
However, there is no display problem for me:

![Screenshot from 2021-06-05 13-00-16](https://user-images.githubusercontent.com/44124798/120889567-1df6a300-c5fe-11eb-9be7-89f080b2e612.png)

**Comment by denismerigoux** [comment]
Using Catala on `master`, I generate this HTML : https://gist.github.com/denismerigoux/889a3f99f5778a7c683fe33c52661e93#file-allocations_familiales-html-L14. If you look on line 14, there is an open `<span class="normal">` just before the `</pre>`. This unbalanced open span is rendered like a blank line on my Firefox browser, creating the display problem : 

![Capture du 2021-06-05 14-48-13](https://user-images.githubusercontent.com/1766128/120892180-3fab5680-c60d-11eb-97b6-e6dc081f6e8c.png)

**Comment by EmileRolley** [comment]
I don't have `<span class="normal">` in my generated files... 

![Screenshot from 2021-06-05 15-45-54](https://user-images.githubusercontent.com/44124798/120893870-adf41700-c615-11eb-9231-fb9a45c614fd.png)

Used commands:
```
catala [master] > make clean
catala [master] > make literate_examples
```

**Comment by denismerigoux** [comment]
Weird. What's your version of Pygments ?

```
> pygmentize -V
Pygments version 2.9.0, (c) 2006-2021 by Georg Brandl, Matthäus Chajdas and contributors.
```

**Comment by denismerigoux** [comment]
Look at the HTML outside the browser, some browser automatically clean up the HTML by removing ill-formed blobs like this unbalanced `span`.

**Comment by EmileRolley** [comment]
> Weird. What's your version of Pygments ?
> 
> ```
> > pygmentize -V
> Pygments version 2.9.0, (c) 2006-2021 by Georg Brandl, Matthäus Chajdas and contributors.
> ```

I had the version `2.6.0` that's why...

**Comment by EmileRolley** [comment]
You just need to replace the `<a.*` by `<.*` on this line:

https://github.com/CatalaLang/catala/blob/113d6a18198b01ef2390ea007b5142ad1aef293d/src/catala/literate/html.ml#L48

**Comment by denismerigoux** [comment]
Thanks Émile, we finally got to the bottom of it :)

**Comment by EmileRolley** [comment]
> Thanks Émile, we finally got to the bottom of it :)

Yes, at least I set up the server :sweat_smile:
