### ISSUE TITLE
MacOS: "Library "re" not found"

### ISSUE THREAD

**Issue by OneManMobile** [CatalaLang/catala#136]
Hi!

Even when installing all dependencies I cannot build the compiler on macOS.

It says:

```
dune build compiler/catala.exe
File "compiler/utils/dune", line 4, characters 34-36:
4 |  (libraries cmdliner ANSITerminal re))
                                      ^^
Error: Library "re" not found.
Hint: try:
  dune external-lib-deps --missing compiler/catala.exe
make: *** [build] Error 1
```

When trying to do "make all" from root. And when I then try: 

`dune external-lib-deps --missing compiler/catala.exe`

Nothing happens and the error still persists when trying the first command.

Great project, hope this is resolvable :) Is it a missing library?

**Comment by OneManMobile** [comment]
Okay, the issue was resolved after running `eval $(opam env)` after installing dependencies.

Maybe this will help someone else :)

**Comment by denismerigoux** [comment]
Could you create a PR to add this to the `README.md` where this would have been useful for you ?
