### ISSUE TITLE
Refactor: new markup for the metadata section

### ISSUE THREAD

**Issue by EmileRolley** [CatalaLang/catala#149]
> Related issue: #147

## The problem

The current syntax to declare _metada blocks_ is the following:
~~~markdown
> Begin metadata
```catala
declaration scope Foo:
  ...
```
> End metadata
~~~

which can leads to confusion (see #147).

## The suggested change

In order to be more intuitive and to stick with the original intent:
 
> [...] Indeed, Metadata blocks are just markers for a specific code blocks that print a "Metadata"-labeled box in the literate programming output, so as to convey to lawyers that this code block is different from "normal" code blocks. [...]
> 
> _Originally posted by @denismerigoux in https://github.com/CatalaLang/catala/issues/147#issuecomment-929914545_

I suggested to replace:

~~~markdown
> Begin metadata
```catala

```
> End metadata
~~~ 

with

~~~markdown
```catala-metadata

```
~~~

### Implementation

This refactoring should only leads to minor modifications in lexers (see [`surface/lexer_*.cppo.ml`](https://github.com/CatalaLang/catala/tree/master/compiler/surface)) and [syntax highlighting files](https://github.com/CatalaLang/catala/tree/master/syntax_highlighting).

**Comment by denismerigoux** [comment]
Closed by #150
