### ISSUE TITLE
Resolve/infer all Any types before format_program

### ISSUE THREAD

**Issue by JMLX42** [CatalaLang/catala#152]
Hi,

I'm writing a Solidity backend to create smart contracts from the Catala code (cf https://github.com/CatalaLang/catala/pull/143).

One of the issues I'm facing is the lack of dynamic typing/type erasure in Solidity to implement things such as the `TAny` type. It works with the Pythonbackend because it has dynamic typing. And it works in OCaml because (I assume) it has type inference. But it won't work in a language that is strongly typed without a costly type erasure abstraction (if that is even possible).

Solidity has strong typing and AFAIK is not capable of having type erasure.

My understanding is that all those `TAny` are most likely typed at some point. At least for type checking.

It would be much better to propagate those types down to the backends and make sure all `TAny` are resolved before calling `format_program`.

**Comment by JMLX42** [comment]
Related issues:

- https://github.com/ethereum/solidity/issues/909
- https://github.com/ethereum/solidity/issues/869

**Comment by denismerigoux** [comment]
## The problem

This issue relates to the fact that currently, the typchecking in `compiler/dcalc/typing.ml` does not save the results of its Hindley-Milner type inference, so the `TAny` that are actually resolved to a specific type remain `TAny` when translation to lower intermediate representation like Lcalc.

## The solution

The AST of `Dcalc` should store the type of every node like the `Pos.t` of every node is stored. Those type cues should be filled at typechecking time such that the functions here

https://github.com/CatalaLang/catala/blob/d301e0f434e744fe0557fcd612b841c448eeeaf6/compiler/dcalc/typing.mli#L18-L20

should have instead the following interface:

```OCaml
val infer_type : Ast.decl_ctx -> Ast.expr Utils.Pos.marked ->  Ast.expr Utils.Pos.marked * Ast.typ Utils.Pos.marked 
  
val check_type : Ast.decl_ctx -> Ast.expr Utils.Pos.marked -> Ast.typ Utils.Pos.marked -> Ast.expr Utils.Pos.marked 
```

**Comment by JMLX42** [comment]
@denismerigoux another question: regarding https://github.com/CatalaLang/catala/issues/204, doesn't it make sense to resolve `TAny` before working on a C backend?

I know type erasure exists in C. But it's not idiomatic. So maybe fixing this issue should be part of moving forward on #204.
