### ISSUE TITLE
Building tutorial_en.pdf fails

### ISSUE THREAD

**Issue by paul-snively** [CatalaLang/catala#167]
On the current master branch, building the tutorial_en.pdf target fails:

```shell
psnively@oryx-pro:~/catala|master⚡ ⇒  make clean build pygments
...
psnively@oryx-pro:~/catala|master⚡ ⇒  cd examples/tutorial_en
psnively@oryx-pro:~/catala/examples/tutorial_en|master⚡ ⇒  make tutorial_en.pdf
...
! You can't use `macro parameter character #' in horizontal mode.
l.71 here, with the "#
                      " symbol. You can define heading of lower
!  ==> Fatal error occurred, no output PDF file produced!
```

ocamlc: 4.12.1
TeX Live 2019/Debian

**Comment by EmileRolley** [comment]
Hi @paul-snively,

thank you for pointing out this issue. This come from the refactoring of the surface syntax introducing new symbols (`#`in this case) which needs to be escaped in the LaTex file.

**Quickfix**: you need to replace all occurences of `#` by `\\#` in `examples/tutorial_en/tutorial_en.tex`.
