### ISSUE TITLE
Format and ANSITerminal interacting poorly

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#174]
The Catala compiler has multiple pretty printers for its intermediate representations that are useful to see what's going on at every compilation stage. These pretty printer use the standard OCaml's `Format` module for indentation and line breakings. However, I also added syntax highlighting using the `ANSITerminal` opam package to make the terminal output more readable.

The problem is that `Format` and `ANSITerminal` seem to interact poorly with each other. Here is what happens with 

    dune exec compiler/catala.exe -- Dcalc -s PrestationsFamiliales examples/allocations_familiales/
    
![Capture d’écran du 2022-01-07 13-25-47](https://user-images.githubusercontent.com/1766128/148543910-158079ec-3a68-4a3b-a00d-70fc33c849a6.png)

And here's the same command using the `--unstyled` option:

![Capture d’écran du 2022-01-07 13-22-30](https://user-images.githubusercontent.com/1766128/148548153-296f4fb9-0eae-4505-b6fa-5154266d3e2b.png)

I have spent some time on a number of occasions trying to debug this but it consistently shows this behavior. Does anybody have some thoughts? @AltGr @EmileRolley?

**Comment by EmileRolley** [comment]
I think it's due to extra characters introduced by `ANSITerminal`, but apart from conditioning the format strings according on the `--unstyled` option I don't know how to fix this. :man_shrugging:

**Comment by denismerigoux** [comment]
`--unstyled` just modifies this:

```ocaml
let print_with_style (styles : ANSITerminal.style list) (str : ('a, unit, string) format) =
  if !style_flag then ANSITerminal.sprintf styles str else Printf.sprintf str
```

**Comment by EmileRolley** [comment]
> `--unstyled` just modifies this:

Yes, but `ANSITerminal.sprintf` will add escaped extra characters for the coloration:
```ocaml
(* ANSITerminal_unix.ml#L199-L206 *)
let to_string style txt =
  let s = "\027["
          ^ String.concat ";" (List.map style_to_string style)
          ^ "m"
          ^ txt in
  if !autoreset then s ^ "\027[0m" else s

let sprintf style = ksprintf (to_string style)
```

consequently, in order to have the right formatting, one format strings needs to be added to consider `ANSI` escaped characters.

For instance: 

```ocaml
  | EMatch (e, es, e_name) ->
      Format.fprintf fmt
        (if not !Cli.style_flag then "@[<hov 2>%a@ %a@ %a@ @[<hov 2>%a@]@]"
        else "@[<hov 2>%a %a %a @[<h 2>%a@]@]")
        format_keyword "match" format_expr e format_keyword "with"
```

**Comment by AltGr** [comment]
Yes, that kind of things happen when functions are trying to align strings based on their length in characters, including ANSI escape codes. I have worked around this issue on a number of occasions so I can have a look. `Format` has specific functions for printing and specifying the display-length at the same time; in opam OTOH we use our own formatting functions that recogniser escape sequences. It's interesting that UTF8 chars are already handled correctly in your case though.

**Comment by denismerigoux** [comment]
If you know a workaround and have time to take a look @AltGr that would be wonderful. Otherwise you can give me a pointer to the workaround and I can try and replicate it in Catala.
