### ISSUE TITLE
Base the Clerk build system on Ninja

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#181]
Following a fruitful discussion with @protz, it appears that we need to think carefully about the evolution of Clerk (the `build_system` folder). Right now, Clerk is just a test harness but as #177 states, the ambition is to make it the `cargo` of Catala with intuitive commands such as `clerk test`, `clerk build`, etc. 

However, the implementation requirements of a proper build system are very tricky: builds have to be parallel and incremental, and should work on every platform including Windows. To avoid replicating boring and cumbersome systems programming development for creating jobs, distributing them, etc. @protz proposed that we simply turn Clerk into a layer on top of https://ninja-build.org/, a sleek build system that operates cross-platform. 

The proposed architecture would imply that Clerk received the command from the user, reads from a manifest file all the necessary options, locations and files that it needs to construct its build graph, and then outputs a Ninja file that it runs to perform the task. 

For this line of work, one needs to understand how Ninja work, and be willing to refactor and expand `build_system/clerk.ml` in OCaml.  An interesting task will also be the design of the Catala manifest files describing the architecture of a Catala project and what its targets are. I'm quite open to suggestions about that, although I have the `cargo.toml` files strongly in my mind.

**Comment by EmileRolley** [comment]
To summarize, the required steps are:

1. Designing the syntax of the manifest file and it's in-memory representation.
2. Refactoring `clerk` to:
  2.1. parse the manifest file
  2.2. build the corresponding data structure
  2.3. translate it into a `build.ninja` file
  2.4. perform the build

Is that correct?

**Comment by denismerigoux** [comment]
Yes indeed! But before that, a good experiment would be to refactor `clerk` such that it performs its testing tasks through a generated `build.ninja` file.

**Comment by EmileRolley** [comment]
> a good experiment would be to refactor `clerk` such that it performs its testing tasks through a generated `build.ninja` file.

It's seems like a good first task for me. If you are okey with it, I can do it.

**Comment by denismerigoux** [comment]
If you're up for it, please have a go! And thanks again for helping the project :)

**Comment by EmileRolley** [comment]
I'm currently experimenting with `ninja`, but I'm not sure of the wanted behavior.
Should `clerk test <dirname>/<filename>` generate a `build.ninja` file containing a rule such as:

```ninja
rule test_s_<scope>
  command = catala Interpret $in -s <scope> --unstyled 2>&1 | colordiff -u -b $out -

build <dirname>/output/<filename>.<scope>.Interpret: test_s_<scope> <dirname>/<filename>
```

before executing from `clerk` the command `ninja <dirname>/output/<filename>.<scope>.Interpret` and printing the result according the returned value?

**Comment by denismerigoux** [comment]
Yep, that sounds about right to me. Bonus points if you can reproduce the counter `<number of tests passed>/<number of tests>` for a whole folder of tests.

**Comment by EmileRolley** [comment]
Wouldn't it be better (easier at least) to run the rules one by one and have clerk counting the number of successful tests?

**Comment by denismerigoux** [comment]
In a single-thread setting yes but the benefits of using `ninja` is to have safe parallel builds (and parallel testing). @protz told me you can use a ninja variable to record the numbers for the counter.

**Comment by EmileRolley** [comment]
Ok, I'll investigate this.

**Comment by msprotz** [comment]
I would assume two phases:
1. Generate a ninja file with all possible targets (possibly relying on checksums or mtimes to make sure everything remains identical in the manifest)
2. Forking over to ninja -- ninja will fail if `colordiff` fails

You might benefit from splitting the rule into (Makefile syntax, to be adapted for Ninja):

```
test_s_foo: foo_actuak foo_expected
 colordiff $^

foo_actual: catala foo
 catala Interpret $< -s foo --unstyled 2>&1 > $@ 
```

**Comment by EmileRolley** [comment]
Finally, using ninja for testing may not be the most appropriate, indeed, the only benefit over a simple script that I see is the native parallelization of the runs. :thinking:

**Comment by denismerigoux** [comment]
Is there not a ninja way like the `.PHONY` Makefile trick to have ninja re-run the tests even if the files have not been modified ? I agree with you the only advantage of `ninja` is to have parallel runes but it's a huge advantage (actually, the biggest advantage of a build system over a script). This experiment with testing is a bit artificial, the advantages will become clearer with compilation rules :)

**Comment by denismerigoux** [comment]
Or we can schedule a meeting with @protz actually, if you're up for it ping me on Zulip and we'll find a timeslot.

**Comment by denismerigoux** [comment]
Relevant : https://github.com/ninja-build/ninja/issues/317#issuecomment-96746431

**Comment by EmileRolley** [comment]
> I f you push what you have done so far I can take a look.

For now, I'm just trying to find the right layout for the generated `build.ninja` file.

**Comment by EmileRolley** [comment]
## Meeting of the 04/02/2022 \w @denismerigoux and @protz 

> Topic: clarify the expected behavior of `clerk` coupled with `ninja`.

When `clerk test <file>` is executed, there are two cases:

* A `ninja.build` file already exists at the project root
  * and the ninja build statement `test_<scope>_<file>` is parts of the
  output of `ninja -t targets rule test_scope` then execute `ninja test_<scope>_<file>`
  -- should we use a module `Ninja.Command` to generate ninja commands?
* Otherwise, scan project  and:
  * generate the corresponding ninja AST -- `Ninja.Ast`,
  * write the `build.ninja` file -- `Ninja.Writer`,
  * call the corresponding ninja command.

At the end, `clerk` only generates a `build.ninja` file and executes `ninja` commands. All the logic (i.e. errors managements, status printing, etc...) of the tests and builds is delegated to `ninja`.
