### ISSUE TITLE
Specifying catala options in Clerk and backend testing

### ISSUE THREAD

**Issue by lIlIlIlIIIIlIIIllIIlIllIIllIII** [CatalaLang/catala#192]
Some features are missing inside clerk 

* The possibility to write tests cases corresponding to specific catala's compiler arguments. For instance `--optimize` or `--avoid_exceptions` modify the compilation results, hence failing the test. Adding other outputs formats (for instance .catala_en.avoid_exception.ml) could solve the problem, but other solution might be better.
* To check if a compilation pass is correct, one way is to check whenever it type-check correctly inside ocaml. To do so, we need at least to import catala.runtime. One solution could be to generate dune files.

**Comment by denismerigoux** [comment]
Maybe @EmileRolley you could tackle this in #186?

**Comment by EmileRolley** [comment]
I think it will preferable to implement this in a separate PR, indeed, I will run out of time. Consequently, I prefer to finish #186 by providing the minimal features first.

**Comment by denismerigoux** [comment]
For the specification of Catala options in Clerk, here is the solution we've chosen. Suppose you have a file `A.catala_en` that you want to test using several unit tests that act on one or more scope of `A.catala_en`, with different combinations of catala compiler options to use. 

Inside `A.catala_en`, you can specify all those unit tests using a little test specification DSL that will be interpreted by Clerk:

```markdown
## Test of foobar

* Mode: Interpret
* Scope: A
* Options: --optimize
```

Using that declaration, Clerk called a first time with `-r` will create an expected output file whose name is the concatenation of the backend, scope and options. Then it will run Catala with the specified options and fill the output file with the output of the command (stdout and stderr mixed).

Next time, calling Clerk without `-r` will parse again the test declaration in the file to test to recreate the Catala command to run, then it will run the Catala command and diff its output against the expected output file created earlier.
