### ISSUE TITLE
Let bindings in Catala

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#203]
## The problem

So far, all Catala variables have to be defined inside the scope system. But sometimes we just want to let-bind a variable locally or define a top-level helper function that does not require the scope machinery

## Local let-bindings

Inside the definition of a scope variable, we want to be able to define a local let-binding like this:

```
scope Foo:
  definition bar equals 
    let baz equals 12 + 3 in 
    baz / 2
```

This can be translated easily to a let-binding expression in Scopelang and Dcalc, whose scoping is limited to this precise definition. The `let ... in` syntax can be translated to `soit ... dans` in French. Or maybe the lawyers think otherwise?

## Toplevel let bindings

While local let-bindings would be really easy to use, top-level let bindings living would require integration into the dependency graph computation, and can only depend on other top-level let binding declarations (not on scopes).

```
let helper_func content type of parameter content type equals ...

let constant content type equals ...
```

We can make type annotations optional but in that case we check that after type checking the inferred type does not contain any free type variable.

**Comment by denismerigoux** [comment]
Feature approved in the Catala meeting of Feb 22nd, 2022. The type annotations could be made optional as long as there is no polymorphism in the inferred types of the top-level let bindings.

**Comment by AltGr** [comment]
I have an attempt at this for local bindings, but we will have to review the syntax. Indeed, the keyword `in` is already used for collections and the prefix `let x equals foo in` is ambiguous:
- it may correspond to the `let` and end the definition of `x` → `let x equals foo in bar`
- or it may be the start of the `MemCollection` predicate → `let x equals (foo in some_collection) [… in bar]`

What solution should we prefer ?
1. Require parentheses (`let VAR equals ( EXPR ) in EXPR`). Not pretty, but easy to implement and does the job
2. Find another syntax for `let in` (`let … inside` ? :unamused:  )
3. Change the current syntax for `MemCollection` ¹. Forces to change existing code but might be the cleanest solution ? Reserving such a keyword for a very specific construct seems a bit overkill to me.

Like for other syntax questions, I guess @denismerigoux should review it with our legal users ?


¹ [Wikipedia](https://en.wikipedia.org/wiki/Element_(mathematics)) gives a handy set of synonymous expressions for English:
> $x \in A$ means that "x is an element of A". Equivalent expressions are "x is a member of A", "x belongs to A", "x is in A" and "x lies in A". The expressions "A includes x" and "A contains x" are also used to mean set membership […]

**Comment by denismerigoux** [comment]
I'm in favor of swiching `x in A` by `A contains x`, it should translate well. Changing existing code is not a problem at this stage, only @protz has code outside the main repo. But we should include a warning in the release notes of the next version anyway. 

You can shoot an email to Sarah with your syntax proposals for English, and to Liane for the French equivalent.

Thanks for handling this !

**Comment by AltGr** [comment]
Proposal corresponding to that suggestion in #297
