### ISSUE TITLE
Providing custom backends for the Catala compiler

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#209]
## The problem

Right now, the backends of the Catala compiler are part of the compiler codebase. Adding a new backend for the compiler requires an external contributor to propose a PR to this repository, then this PR has to be accepted and merged into `master`; this new backend will then be shipped with all Catala compiler binaries and available to all.

This current workflow is adapted to general-purpose backends that target popular programming languages. We want Catala users to enjoy having multiple backends to choose from out of the box, covering all their favorite languages.

However, this workflow is not adapted to an actual industrial adoption of Catala by an organization with an established IT system. Indeed, one of the great benefit of having a DSL is to be able to custom tailor the generated code to the precise use that is required. For instance, industrial users of Catala will want to tweak the C/Python/Javascript backend to use in-house classes, types and methods rather than the ones provided by the Catala runtime. Industrial users might want to get rid (at their own risk) of the infinite-precision GMP-based runtime in favor of fixed-precision integers or (don't do that please) float.

For those industrial users, custom backends should be written as plugins of the Catala compiler, without having to merge in the public `master` branch. Indeed, the code of these custom backend might contain sensitive information about the shape of a closed-source codebase. So the code for these custom backends pluging should stay out of the public Catala repository and maintained by the industrial users themselves.

The question is: can we devise a system in OCaml that would allow these user to supply their own custom backends to link against the Catala compiler? Maybe something involving first-class modules? @protz @AltGr I'm curious to hear your opinion on that.

**Comment by AltGr** [comment]
The most obvious approach could be to use dynamic linking: compile the given backend as a shared object that calls a function `Catala.Driver.register_dyn_backend <backend>` with a given fixed type for `<backend>` (e.g. `Lcalc.Ast.t -> unit`, or, indeed, a first-class module with a given signature). Then provide an option from the CLI to load the shared object and use the backend registered through the side-effects of the `register_dyn_backend` function.

**Comment by EmileRolley** [comment]
Closed by #213
