### ISSUE TITLE
Breaking changes with new release of bindlib

### ISSUE THREAD

**Issue by rlepigre** [CatalaLang/catala#211]
To avoid breakage, you will need to constrain the bindlib version used by catala to be exactly 5.0.1 due to the release of 6.0.0, which contains some changes of API and semantics. I can help porting the code to version 6.0.0 once the package is published.

There is already a PR for publishing Bindlib 6.0.0 (see https://github.com/ocaml/opam-repository/pull/20808), and I took care of constraining the existing catala versions to bindlib 5.0.1 there.

**Comment by denismerigoux** [comment]
Thanks very much @rlepigre, it's very kind of you to warn us about breaking changes in your library. Thanks for constraining the version number on `opam`, I'll leave this issue opened as a reminder to upgrade our codebase to `6.0.0`. @lIlIlIlIIIIlIIIllIIlIllIIllIII I guess this new version contains the fixes you submitted :)
