### ISSUE TITLE
Out of date French documentation

### ISSUE THREAD

**Issue by jemsab** [CatalaLang/catala#24]
The documentation for writing Catala with French keywords is out of date, mainly some keywords are missing compared to the English version.

Per Denis' remarks in PR#23, the reading guide should be written as HTML rather than in LaTeX because we want it to appear here : https://catala-lang.org/en/guide. There's already a tutorial for programmer that showcases most of the syntax here : https://catala-lang.org/en/examples/tutorial. 

I would imagine the English versions are considered the reference versions. If that is indeed the case, it might be easiest to simply translate the English versions, taking special care to maintain the French keywords as they are already used. 

What do you think? If that is ok with you I can help out by doing some translation.

**Comment by denismerigoux** [comment]
Hi James,

Thanks for contributing ! Indeed the first thing to do would be to translate the English programmer's tutorial into French. You can do so by duplicating the `examples/tutorial` folder into `examples/tutorial_en` and `examples/tutorial_fr`, and translate the contents of `examples/tutorial_fr`. 

If you're up for starting this, that would be wonderful.

**Comment by denismerigoux** [comment]
@jemsab now that I've done a full documentation pass I think the tutorial is stable enough to consider a translation to French.

https://github.com/CatalaLang/catala/blob/master/examples/tutorial/tutorial_en.catala_en
