### ISSUE TITLE
Improving trace displaying for Catala programs

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#243]
## The current situation

The Catala compiler can be called with the `-t` or `--trace` option. When enabled, this option inserts logging calls in the Catala code such that when executed, an execution trace of all these logging calls is built. 

Here is the result with the interpreter : https://asciinema.org/a/385884.

With the Python script, the log is retrieved and displayed on the command line when running `python main.py show_log` with the following code: https://github.com/CatalaLang/catala/blob/b20b2f97be0963fce3a600c9d5438b2f4df63d6a/french_law/python/main.py#L70-L85

With the JS script, the log in JSON format can be printed with this blog of code: https://github.com/CatalaLang/catala/blob/b20b2f97be0963fce3a600c9d5438b2f4df63d6a/french_law/js/allocations_familiales.js#L31-L39

## How to improve things ?

This tracing feature can be reused in order to provide an individual explanation of how the Catala program reached its final conclusion, step by step showing which legislative articles were used to make progress on the computation. Indeed the log events contain the position in the source code in terms of lines and columns but also the place inside the hierarchical structure of the legislative document where this piece of code is.

**Comment by rprimet** [comment]
A nice first step might be to document the JSON trace production starting from an arbitrary catala file (e.g. the first tutorial)

IIUC, Javascript is not a backend for catala (yet?) so the way this works is that the catala compiler is compiled to JS, and then interprets a program.

Starting from a catala file, how would one generate the JS blob that contains the interpreter and the program to interpret, and run a given scope (maybe with arguments) with logging enabled? (either using the browser or node?)

The `Makefile` seem to have related instructions [here](https://github.com/CatalaLang/catala/blob/master/Makefile#L210-L213): but they are a little arcane to me

```
#> build_french_law_library_js		: Builds the JS version of the OCaml French law library
build_french_law_library_js: generate_french_law_library_ocaml format
	dune build --profile release $(FRENCH_LAW_OCAML_LIB_DIR)/api_web.bc.js
	cp -f $(ROOT_DIR)/_build/default/$(FRENCH_LAW_OCAML_LIB_DIR)/api_web.bc.js $(FRENCH_LAW_JS_LIB_DIR)/french_law.js
```

WDYT?

Tangential thought: would it be worth ensuring that all backends can emit JSON in a consistent format? (e.g. for inter-backend comparisons/debugging?)

**Comment by denismerigoux** [comment]
## How to compile Catala to Javascript?

Say that you have a file named `foo.catala_en` that you want to compile to JS. Let's also say that you have built the Catala compiler and it can be called with the `catala` binary from the shell (with the current setup you can call it with `dune exec compiler/catala.exe --`.

First you have to produce an OCaml file from the `foo.catala_en` file with:

    catala OCaml -t -O foo.catala_en
    
This produces `foo.ml` with the OCaml code corresponding to `foo.catala_en`. Now, you can't simply compile that to JS with `js_of_ocaml`, because you won't be interoperate with other Javascript code if you compile it in this "raw" way. What you have to do is to write a wrapper, in OCaml, that glues together the interface of `foo.ml` with a Javascript-facing interface that receives and produces Javascript objects. An example of such a wrapper is https://github.com/CatalaLang/catala/blob/master/french_law/ocaml/api_web.ml, it uses the bindings in OCaml provided by `js_of_ocaml`. The documentation about how to use these bindings and write the wrapper is here: https://ocsigen.org/js_of_ocaml/latest/manual/rev-bindings.

Let's sat that you finally have written this wrapper `foo_web.ml`, alongside `foo.ml`. Then you can proceed to compile both files to Javascript. For that, we use the `dune` build system in OCaml with a declaration inside a file named `dune` that tells us how to compile these OCaml files to Javascript:

```
(executable
 (name foo_web)
 (modes byte js)
 (modules foo_web foo)
 (preprocess
  (pps js_of_ocaml-ppx))
 (libraries catala.runtime js_of_ocaml))
```

Now that we have described what to compile, we call the `dune` compilation with:

    dune build foo_web.bc.js

This produces the file `_build/default/foo_web.bc.js` that is the JS binary that we wanted all along. Then, you can import this JS binary as a node module or inside your browser and call the functions it exports, as you've defined them in `foo_wrapper.ml`. 

## How to get the trace in Javascript

Since you've used the `-t` option of the catala compiler, `foo.ml` will contain logging calls that will automatically record all the events at execution and stored them in an OCaml object. If you want to retrieve this log as a Javascript object, you need to provide a wrapper that transforms the OCaml object into a Javascript object (that you can put in `foo_web.ml`). This code does it for instance: 

https://github.com/CatalaLang/catala/blob/b20b2f97be0963fce3a600c9d5438b2f4df63d6a/french_law/ocaml/api_web.ml#L142-L194

Once you've defined `retrieveLog` in `foo_web.ml`, and compile `foo_web.ml` into `foo_web.bc.js`, you can call `retrieveLog` in Javascript and retrieve the log as a JSON object.

## The `french_law` library

This process is quite burdensome, and probably not optimal for the future; providing a native JS backend for the Catala compiler would be better. However this process has been implemented for the `french_law` library. By calling 

    make build_french_law_library_js
    
from the root of the Catala repository, `make` will replay all the compilation steps of this process for you, given that the wrapper in `french_law/ocaml/api_web.js` has been correctly written manually. This `make` invocation also places the resulting `api_web.bc.js` JS binary into `french_law/js`.

## About uniformity of JSON log formats across all backends

> Tangential thought: would it be worth ensuring that all backends can emit JSON in a consistent format? (e.g. for inter-backend comparisons/debugging?)

Yes that sounds good! Maybe you could define a JSON schema based on 

https://github.com/CatalaLang/catala/blob/b20b2f97be0963fce3a600c9d5438b2f4df63d6a/french_law/ocaml/api_web.ml#L57-L73

The difficult thing to define in such a JSON schema is what is inside `loggedValue` since it can contain any Catala runtime value. Catala runtime values can be:
* integers
* decimal
* money values
* dates 
* durations
* boolean
* enumerations
* structs
* arrays

This embedding is defined here

https://github.com/CatalaLang/catala/blob/b20b2f97be0963fce3a600c9d5438b2f4df63d6a/compiler/runtime.mli#L49-L60

**Comment by EmileRolley** [comment]
I don't know if we can consider the issue as completed, however, here is a list of related improvements on the OCaml/JS side:
+ Use `yojson` to serializes runtime values: #267
+ A new log event structure: #280 and #283
+ A new `api_web` plugin and JSOO runtime: #291 

All this compiler improvements have been used for the [catal-website](https://github.com/CatalaLang/catala-website) to implement a [log event visualizer](https://catala-lang.org/en/examples/family-benefits/visualization) -- see https://github.com/CatalaLang/catala-website/pull/25.
