### ISSUE TITLE
Feature request: multiplication of durations

### ISSUE THREAD

**Issue by kescher** [CatalaLang/catala#269]
I would appreciate an operator that can multiply durations, such as `*^` with the English syntax (duration) *^ (integer). 

This has come up in attempts to formalize some Washington state laws. E.g., [RCW 46.61.5055(11)(b)](https://apps.leg.wa.gov/rcw/default.aspx?cite=46.61.5055): "For each violation of mandatory conditions of probation under (a)(i), (ii), (iii), (iv), or (v) of this subsection, the court shall order the convicted person to be confined for thirty days, which shall not be suspended or deferred." A duration multiplication operator would allow us to get the total confinement period, which is 30 days times the number of probation violations.

**Comment by msprotz** [comment]
@kescher to add an operator, let's look at what is done for "/^":

(you can take inspiration from this PR: https://github.com/CatalaLang/catala/pull/251/files as well)

- in compiler/surface, extend the lexer: search for DIVDURATION, find out where the token is defined, add MULDURATION, and extend around line 622
- in the parser (parser.mly), extend the class of multiplicative operators following DIVDURATION
- and from here on, follow the compiler errors as you try to compile your code:
  - extend the AST with a new operator (ast.ml and ast.mli)
  - extend interpreter (interpreter.ml), printer (print.ml) and type-checker (typing.ml)
  - extend ocaml extraction (to_ocaml.ml)
- add tests

I'm available to help if these instructions are too terse. Let me know!

**Comment by AltGr** [comment]
You might prefer to implement `duration *^ decimal`, which would make sense and be more general.

**Comment by denismerigoux** [comment]
The rounding semantics of `duration *^ decimal` is not easy : what is `3 month *^ (1/2)` ? `1 month`, `2 month`, `1 month 15 days`, `1 month 16 days` ?

**Comment by AltGr** [comment]
ha indeed :thinking:
