### ISSUE TITLE
Ubuntu build failing

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#281]
There appears to be a problem when installing the `conf-npm` opam package ?

https://github.com/CatalaLang/catala/runs/6966132308?check_suite_focus=true#step:5:5540

**Comment by denismerigoux** [comment]
Now that we have CI that rebuilds from a docker image we can remove the ubuntu build ? https://github.com/CatalaLang/catala/runs/7430504748?check_suite_focus=true

**Comment by AltGr** [comment]
I guess we could… I am not sure it adds much; and it should be possible to extract artifats from the routine builds.

The new dockerised tests are based on Alpine, not Ubuntu though. It's better for portable binaries but the specifics of the dependencies etc. are different. I'd argue that the OCaml test image that we were using is pretty specific anyway ?

**Comment by denismerigoux** [comment]
I would prefer to have a Mac (or even a Windows) build than re-testing on Ubuntu... If it builds on Alpine I'd say it should work for Linux.

**Comment by denismerigoux** [comment]
Fixed by #298
