### ISSUE TITLE
List concatenation operator

### ISSUE THREAD

**Issue by msprotz** [CatalaLang/catala#301]
It would be convenient to have a list concatenation operator. The infix, right-associative operator `@` like in OCaml could be used, or `++` like in Haskell would work as well.

**Comment by denismerigoux** [comment]
I'm actually in favor of `++`. Will implement it today.

**Comment by denismerigoux** [comment]
Wait, duplicate of #109 and already fixed by #137. Just use `++` :)

**Comment by msprotz** [comment]
Thanks Denis!
