### ISSUE TITLE
Unable to find catala.py

### ISSUE THREAD

**Issue by DavidPratten** [CatalaLang/catala#307]
I'm working on trying out tutorial_en.py generated by 

```
catala Python --scope=Test1 tutorial_en.catala_en
```

Following the documentation here https://github.com/CatalaLang/catala#api , here https://github.com/CatalaLang/catala/blob/master/french_law/README.md and here https://github.com/CatalaLang/catala/blob/master/french_law/python/README.md I have found this guidance

> The Python files generated by the Catala compiler expect the presence of the src/catala.py file which contains the definitions of the values and operations used by the generated code.

However I have been unable to find catala.py in compiler output or the repository.

Thanks

David

**Comment by EmileRolley** [comment]
Hi @DavidPratten, it looks like `src/catala.py` has been renamed to `src/runtime.py`. 

The documentation must be updated, thanks for pointing it out!
