### ISSUE TITLE
LaTeX output not appear to be complete

### ISSUE THREAD

**Issue by DavidPratten** [CatalaLang/catala#308]
Hi Team,

When building a PDF from Catala LaTeX output for example [eg1.tex.txt](https://github.com/CatalaLang/catala/files/9276510/eg1.tex.txt) I get errors from [Texmaker](https://www.xm1math.net/texmaker/) and also from [Interactive LaTeX Editor](https://arachnoid.com/latex/).

I couldn't find anything in the repo that may help. I'd appreciate any pointers!

All the best,

David

**Comment by denismerigoux** [comment]
As you can see from the LaTeX file produced by the compiler this is not a complete LaTeX document but rather only a blob intended to be embedded inside a complete LaTeX document. For the Catala compiler to produce a complete LaTeX document, you need to call it with the `-w` or `--wrap` option who is document here: https://catala-lang.org/en/doc/catala.
