### ISSUE TITLE
Node/JS artifact of the Catala compiler should be made without Z3

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#311]
The artifacts created by 

https://github.com/CatalaLang/catala/blob/master/build_release.sh#L41

include a Node/JS version built with `dune build compiler/catala.bc.js`. This artifact should only be built with an opam environment where `z3` is NOT installed, otherwise the artifact fails with error messages of the type:

```
Fatal error: exception Failure("caml_thread_initialize not implemented")
```

**Comment by AltGr** [comment]
Hmm indeed makes sense obviously :facepalm:
