### ISSUE TITLE
Rather unfortunate project name

### ISSUE THREAD

**Issue by guillemj** [CatalaLang/catala#360]
Hmm, the name of this programming language seems rather unfortunate, as there is an actual natural language with the same name (Català in Catalan). Imagine creating the `Français Programming Language`. :)

This seems like lots of confusion waiting to happen, so I'd urge you to find a different name, even though I realize how painful that can be, but the earliest this kind of thing is done the better I'd say.

**Comment by denismerigoux** [comment]
Hi Guillem,

Thank you for pointing this out. As written in the `README` of the project : 

> The language is named after Pierre Catala, a professor of law who pionneered the French legaltech by creating a computer database of law cases, Juris-Data. The research group that he led in the late 1960s, the Centre d’études et de traitement de l’information juridique (CETIJ), has also influenced the creation by state conselor Lucien Mehl of the Centre de recherches et développement en informatique juridique (CENIJ), which eventually transformed into the entity managing the LegiFrance website, acting as the public service of legislative documentation.

Hence the name "Catala" (without `à`) is something of deep significance to the project team. We know about the typographic closeness with the way the Catalan language designates itself in Catalan. We even included a note on the website of the project : https://catala-lang.org/en/about.

> Beware, the name Catala is typographically close to the name of the Catalan language written in Catalan : Català. However, the very narrow scope of our programming language should not be prone to set any confusion given the existing wide influence of the Catalan language and culture.

Indeed our programming language is domain-specific and does not have any ambition of being adopted by a large number of users, contrary to the Catalan natural language :)
