### ISSUE TITLE
Overriding functions in subscopes under condition always apply the override

### ISSUE THREAD

**Issue by adelaett** [CatalaLang/catala#362]
# The problem

The problem comes from the interaction between lambda abstraction and default constructor.

The following code have two scopes. The callee contains a function `input_v`, whom result is computed and returned by the scope, and a caller whom call the scope with some arguments. The caller want to override the function `input_v` of the callee under specific conditions depending on arguments of the function.

```catala
declaration scope Callee:
  context input_v content integer depends on boolean
  context output output_v content integer

declaration scope Caller:
  sub scope Callee
  context output y content integer

scope Callee:
  definition input_v of b equals if b then 0 else 1
  definition output_v equals input_v of false + 1

scope Caller:
  definition sub.input_v of x under condition x consequence equals 0
  definition y equals sub.output_v
```

Down the line in the Dcalc intermediate representation, the expected behavior is the following. The callee check if the function overrode return an empty on its arguments, and if it is the case, switch back to the default behavior. However, the observed behavior is the program always crash with an "Unexpected Empty" if the condition is not satisfied.

Indeed the translation of the line  `definition sub.input_v of x under condition x consequence equals 0` is the following dcalc expression, passed as argument to the Callee scope instance

```ocaml
    let sub.input_v : unit → bool → integer =
      λ (_: unit) → λ (param: bool) → error_empty ⟨param ⊢ 2⟩ in
```

And the translation of the callee is 

```ocaml
    let input_v : bool → integer = error_empty
      ⟨input_v () | true ⊢
        λ (param: bool) → error_empty
          ⟨true ⊢ if param then 0 else 1⟩⟩ in
    let output_v : integer = error_empty
      ⟨output_v () | true ⊢ ⟨true ⊢ input_v false  + 1⟩⟩ in
```

Hence, the definition inside Callee is always overrided by the line `<input_v () | true |- ...>` since `input_v` is always a value (a function). and the example crashes when executed.

# A not-working fix

Removing error_empty in the definition of sub.input_v does not work either, since the line `<input_v () | true |- ...>` always override the function defined inside the callee.

**Comment by denismerigoux** [comment]
Hi Alain, thanks for reporting this error ! The encoding from Desugared to Scopelang for context variables which are also functions is indeed wrong. For this example, the correct fix is the following :


```ocaml
Inside Caller :
    let sub.input_v : bool → integer =
      λ (param: bool) → ⟨param ⊢ 2⟩ in
 ```
 
 ```ocaml
 Inside Callee:
     let input_v : bool → integer = error_empty
       λ (param: bool) → ⟨input_v param | true ⊢
         error_empty ⟨true ⊢ if param then 0 else 1⟩⟩ in
 ```
 
 Basically we don't need to thunk those context variable who are themselves functions when passing them from the caller to the callee. I'll try and fix the encoding in the implementation of Desugared -> Scopelang tomorrow or Friday.
