### ISSUE TITLE
Backend functions for date calculations do not always behave correctly

### ISSUE THREAD

**Issue by rmonat** [CatalaLang/catala#398]
Each backend has functions/relies on libraries to perform date calculations. They do not always behave as we expect (the runtime and the `dates-calc` libraries act as references, until we write up a paper with a clear semantics).

An issue has been spotted and fixed in #396 already. The date addition in Python round downs according to my experiments. The rest of the Python backend seems fine.

(I don't have permission to self-assign but I can take a look if fixes are not urgent)

**Comment by denismerigoux** [comment]
Yeah right now the Python backend uses Python's date library but we should switch to a Python port of https://github.com/CatalaLang/dates-calc.

**Comment by rmonat** [comment]
Following #397, the date rounding option is not available in this current backend.

**Comment by rmonat** [comment]
Python implementation ready for review in https://github.com/CatalaLang/dates-calc/pull/1

**Comment by rmonat** [comment]
Okay, `dates-calc` 0.0.5 is now available in opam!
