### ISSUE TITLE
Afficher les résultats intermédiaires d'un test pour les AL locatif

### ISSUE THREAD

**Issue by JusBanuls** [CatalaLang/catala#444]
Essai sur le test des AL locatif à SPM d'afficher les résultats intermédiaires, échec.

Cela provient probablement du champ d'application des AL pour le secteur locatif qui renvoie aux APL du secteur locatif.
https://github.com/CatalaLang/catala/blob/3c687ab28ca902a1707f8a853da6ca306e1bee84/examples/aides_logement/tests/tests_calcul_al_locatif.catala_fr#L121-L128

**Comment by denismerigoux** [comment]
J'ai corrigé dans le commit ci-dessus et maintenant ça affiche bien les résultats intermédiaires. Par contre les valeurs sont erronnées, par exemple Catala calcule `0.0238` au lieu de `0.02685` pour `taux_composition_familiale` et le montant final de l'aide est `137.69 €` au lieu de `138.24 €`.

**Comment by JusBanuls** [comment]
Oui, j'ai confondu le taux familial et le taux de participation personnelle, je corrige. En revanche, sur le résultat final, j'ai l'impression que la contribution au remboursement de la dette sociale (CRDS) n'est pas effectuée dans le calcul, ce que je n'arrive pas à expliquer.
C'est ce qui explique la différence dans tous les cas.

**Comment by denismerigoux** [comment]
Closed by [#9c](https://github.com/CatalaLang/catala/commit/9c262ca8efc0d994aad13d40f2ed183f693259a9)
