### ISSUE TITLE
invalid default term constructed when multiple definitions of the same variable

### ISSUE THREAD

**Issue by adelaett** [CatalaLang/catala#449]
According to the documentation, when writing twice to same variable should build the following default term `⟨3 | false ⊢ ∅ ⟩`. However, the current master compiles to `⟨⟨⟨true ⊢ 3⟩ | true ⊢ 3⟩ | false ⊢ ∅ ⟩`, and the current adelaett-withoutexceptionsfix branch compiles it as `⟨3, 3 | false ⊢ ∅ ⟩`. 

```bash
> cat tests/test_default/good/mutliple_definitions_equal.catala_en
declaration scope A:
  output w content integer

scope A:
  definition w equals 3

scope A:
  definition w equals 3
```

```bash
> dune exec compiler/catala.exe --display=quiet -- Dcalc tests/test_default/good/mutliple_definitions.catala_en -s A
let A =
  λ (A_in: A_in {}) →
    let w : integer = error_empty
      ⟨⟨⟨true ⊢ 3⟩ | true ⊢ 3⟩ | false ⊢ ∅ ⟩ in
    A { "w"= w }
```

```bash
> dune exec compiler/catala.exe --display=quiet -- Dcalc tests/test_default/good/mutliple_definitions.catala_en -s A
let scope A (A_in: A_in): A =
  let set w : integer = error_empty ⟨3, 3 | false ⊢ ∅ ⟩ in 
  return { "w"= w }_A
```

here is an example when the two definitions are not equal. The expected behavior should be to raise an error.

```bash
> cat tests/test_default/bad/mutliple_definitions_different.catala_en
declaration scope A:
  output w content integer

scope A:
  definition w equals 3

scope A:
  definition w equals 4
```

This one builds the correct term in both branches.

**Comment by AltGr** [comment]
Not directly answering here, but reacting to the `⟨3, 3 | false ⊢ ∅ ⟩` version: I think it's worth it to keep the invariant that exceptions in default terms should always be default terms. While not required by the defined semantics, it gives a stronger structure and opens the way to having simpler, equivalent semantics implementation-wise — _e.g._ only propagating $\emptyset$ through nested default terms could avoid the need for full-fledged exceptions support in the backend or lower passes.

More on the question, the choice of this encoding was made on 9ef8625 after discussions in #208. The goal was to be more tolerant on conflicting exceptions "that don't matter".

**Comment by AltGr** [comment]
(I agree it would be nice to better reflect this "semantic sugar" in the semantics though!)

**Comment by adelaett** [comment]
> I think it's worth it to keep the invariant that exceptions in default terms should always be default terms
If we disable traces, this invariant does not hold anymore. You have an idea why ?

Also, why `⟨⟨⟨true ⊢ 3⟩ | true ⊢ 3⟩ | false ⊢ ∅ ⟩` was chosen instead of `⟨3 | false ⊢ ∅ ⟩` or `⟨⟨| true ⊢ 3 ⟩ | false ⊢ ∅ ⟩` ?

**Comment by adelaett** [comment]
I've find the issue: when deactivating traces, the smart constructor make_default simplify the default term. This case is then not handled correctly by the collapsing of exceptions.
