### ISSUE TITLE
broken link in the documentation

### ISSUE THREAD

**Issue by zapashcanon** [CatalaLang/catala#504]
Hi,

[Here](https://catala-lang.org/ocaml_docs/catala/plugins.html), the `Driver.Plugin` link, after:

> See the following module for the registration interface:

Is broken (the home page is displayed somehow).

EDIT: same [here](https://catala-lang.org/ocaml_docs/catala/Driver/) when clicking on the `Plugin.PluginAPI` link.

**Comment by denismerigoux** [comment]
Weird, I can't reproduce by doing `make doc` on my machine and inspecting the generated HTML. @AltGr ?

**Comment by AltGr** [comment]
Should be fixed by https://github.com/CatalaLang/catala-website/pull/57 which redirects the whole doc to the nightly CI-generated https://catalalang.github.io/catala/api-doc/
