### ISSUE TITLE
The first example in README.md appears wrong

### ISSUE THREAD

**Issue by amluto** [CatalaLang/catala#514]
README.md contains [an example](https://github.com/CatalaLang/catala/blob/master/doc/images/ScreenShotVSCode.png), which is (oddly) a PNG.  It says:

> If the property was acquired by gift after December 31, 1920, the basis shall be the same as it would be in the hands of the donor or the last preceding owner by whom it was not acquired by gift, except that if such basis (adjusted for the period before the date of the gift as provided in section 1016) is greater than the fair market value of the property at the time of the gift, then for the purpose of determining loss the basis shall be such fair market value.

IANAL, and I am not a tax expert, but I'm somewhat confident that the words "for the purpose of determining loss" are intentional. But the Catala translation seems to ignore that part!

**Comment by denismerigoux** [comment]
Hi @amluto, thanks for this! The image of the README was 2,5 years old and taken at the beginning of the project on an early example from the US Tax Code. We weren't able to find proper legal expertise to review the code and ensure it's correct and up to date so we just removed this example (and others) : https://github.com/CatalaLang/catala/pull/480. I updated the README picture to a example we actively maintain now.
