### ISSUE TITLE
Implement maximum and minimum aggregation function

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#52]
Catala supports `maximum` and `minimum` aggregation functions for collections. Right now, these are only present in the surface syntax.

One has to fill the holes like this one : 

https://github.com/CatalaLang/catala/blob/933fd024842993f2f458f132e12f480c875b8d38/src/catala/catala_surface/desugaring.ml#L362-L364

To do that, the expression `maximum money for salary in salaries of (salary - $200)` should desugar to 

```
fold (fun acc salary -> let tmp = (salary - 200) in if acc < tmp then tmp else acc) <INIT> salaries
```

The problem lies within the `<INIT>` expression. What to put here? I guess this should be provided by the user, so we have to update the syntax to something like `maximum money context $0 for salary in salaries of (salary - $200)`

**Comment by nchataing** [comment]
What should the extremum of an empty collection returns ? If it raises an error, then we could take any element of the collection for the `<INIT>` expressions.

**Comment by denismerigoux** [comment]
In case of an empty collection, it should return `<INIT>` precisely, that's why we need an `<INIT>`

**Comment by denismerigoux** [comment]
I'm not confortable with forcing collections to be non-empty. Then it would force us to wrap collections in option types, which is cumbersome.
