### ISSUE TITLE
Publish VS Code extension(s)

### ISSUE THREAD

**Issue by samestep** [CatalaLang/catala#596]
Hello! I'm using VS Code, but when I [searched in the Marketplace](https://marketplace.visualstudio.com/search?term=catala&target=VSCode) for a Catala extension, I didn't find anything, so I assumed it didn't exist. Then my friend pointed out that Catala does indeed have VS Code extensions for [French](https://github.com/CatalaLang/catala/tree/0.9.0/syntax_highlighting/fr/vscode) and [English](https://github.com/CatalaLang/catala/tree/0.9.0/syntax_highlighting/en/vscode), but the user needs to manually build and install them. It would be nice for these extensions to be published to the VS Code marketplace (perhaps after combining them into a single extension?) for easier discoverability and installation.

I have experience building and publishing VS Code extensions, so I am happy to open a pull request to do most of the work for this; it shouldn't take long. The only parts that I can't do myself would be to create an Azure DevOps organization, VS Code publisher, and personal access token for publishing, as described on [this page](https://code.visualstudio.com/api/working-with-extensions/publishing-extension). Once those are done, I could include in my pull request a GitHub Actions workflow that triggers on release, which automatically publishes the VS Code extension(s) to the Marketplace.

**Comment by AltGr** [comment]
Hello, and thanks a lot for proposing to contribute in this way.

Indeed, publishing to the VScode marketplace would be helpful, and we gladly accept your proposition. I'll be creating the organisation on Azure in the meantime.

**Comment by denismerigoux** [comment]
@AltGr were you able to create an Azure org?
