### ISSUE TITLE
Default optimizations missing some cases?

### ISSUE THREAD

**Issue by rmonat** [CatalaLang/catala#609]
Tried on catala `main`, commit `e8820d79b8028fbaa9f9193cf94ae2344f09abe4`.

Let us consider this testcase, courtesy of @pierregoutagny:
```catala_en
## Article

```catala
declaration scope A:
    input b content boolean
    output o content integer

scope A:
    definition o under condition b consequence equals 1
    exception definition o under condition not b consequence equals 0
``````

I ran 
```
dune exec catala -- Python --optimize except_one.catala_en
```

The Python output contains
```python
        def temp_o(_:Unit):
            def temp_o_1(_:Unit):
                return integer_of_string("1")
            def temp_o_2(_:Unit):
                return b
            return handle_default(SourcePosition(filename="except_one.catala_en",
                                  start_line=6, start_column=12,
                                  end_line=6, end_column=13,
                                  law_headings=["Article"]), [], temp_o_2,
                                  temp_o_1)
        def temp_o_3(_:Unit):
            return True
        def temp_o_4(_:Unit):
            def temp_o_5(_:Unit):
                return integer_of_string("0")
            def temp_o_6(_:Unit):
                return not b
            return handle_default(SourcePosition(filename="except_one.catala_en",
                                  start_line=6, start_column=12,
                                  end_line=6, end_column=13,
                                  law_headings=["Article"]), [], temp_o_6,
                                  temp_o_5)
        temp_o_7 = handle_default(SourcePosition(filename="except_one.catala_en",
                                  start_line=6, start_column=12,
                                  end_line=6, end_column=13,
                                  law_headings=["Article"]), [temp_o_4],
                                  temp_o_3, temp_o)
```

I'm a bit confused about the last `handle_default`: given there is a single exception `temp_o_4`, why isn't this default removed?

I'm interest in removing those because its skews the coverage measurement for the concolic testing engine we are trying.

**Comment by adelaett** [comment]
Thanks for your report.

In this example, the dcalc intermediate form is

```
dune exec catala -- dcalc --optimize catala-609.catala_en
```

```
let A : A_in → A =                     
  λ (A_in: A_in) →
  let b : bool = A_in.b_in in
  let o : integer = error_empty ⟨ ⟨~ b ⊢ ⟨0⟩⟩ | true ⊢ ⟨b ⊢ ⟨1⟩⟩ ⟩ in
  { A o = o; }
in
A
```

Currently, the compiler does not have the knowledge that both `~b` and `b` contradict each other. Hence it cannot optimize those case. If both `~b` and `b` are true at the same time, the program with prioritize the first exception, returning `0` without evaluating the second exception. This is the intended behavior for now, as we might build more aggressive optimization pass later.

The example you gave is slightly different from the Zulip: here `temp_o_3` is `lambda (): True`, while in your Zulip example it was `lambda (): False`. If you show us the original program, i can take a look at it :)

Best

--

Alain

**Comment by rmonat** [comment]
Thank you Alain for your answer! 

> The example you gave is slightly different from the Zulip: here temp_o_3 is lambda (): True, while in your Zulip example it was lambda (): False. If you show us the original program, i can take a look at it :)

Yes, the original program was generated on an older version of catala. I had not updated our concolic branch to sync it with main, sorry about that.

I'm closing it for now, although I plan to investigate some other cases where the code is generated.
