### ISSUE TITLE
Suport for composite catala duration literals in the parser

### ISSUE THREAD

**Issue by rprimet** [CatalaLang/catala#705]
This is just a reminder that the issue at https://github.com/CatalaLang/catala-language-server/blob/9f9cf066dcd999fe83f8586012d87d7a3093461f/test-case-parser/test_case_parser_lib_atd.ml#L279 needs fixing so that we can do round-trip test edits

**Comment by denismerigoux** [comment]
ah indeed!

**Comment by denismerigoux** [comment]
Workaround found with https://github.com/CatalaLang/catala-language-server/pull/29 : we just parse the addition of duration literals.
