### ISSUE TITLE
Improvements for the Catala formatter

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#709]
## Among

```
champ d'application BénéficesNonCommerciauxFoyerFiscal:
  définition solde_net_global_non_professionnel
    état agrégation
    égal à
      somme argent de résultat_liquidation.solde_net_non_professionnel
        pour résultat_liquidation parmi résultats_liquidation_bénéfices_non_commerciaux
```

If I split `pour résultat_liquidation parmi résultats_liquidation_bénéfices_non_commerciaux` into two lines, the formatters puts it back on the same line. Ditto with ` somme argent de résultat_liquidation.solde_net_non_professionnel`.

## Result of with

```
(
      résultat de PrélèvementPlusMoinsValueLongTermeBénéficesIndustrielsCommerciaux avec {
       ...
      }
    ).prélèvement_libératoire
```
The formatter does not let me split `résultat de PrélèvementPlusMoinsValueLongTermeBénéficesIndustrielsCommerciaux avec {` on two lines.

## Definition 

```  
définition pro_rata_plancher_abattement_forfaitaire_total.montant_à_distribuer égal à
```

The formatter does not let me split this into multiple lines.

## Dots and splits

```
 + revenus.non_professionnels.locations_meublées_micro_classées_rurales_spéciales
 ```
 
 The formatter should let me split this long ident with `.` to multiple lines
 
 ```
 + revenus.
   non_professionnels.locations_meublées_micro_classées_rurales_spéciales
 ```
 
 The syntax highlighter should correctly color the identifier avec the `.` and the line break.
 
## Equal indent 

```
champ d'application TraitementsSalairesDéclarant:
  définition assiette_exonérations_81_quater
    état art_81_quater
    égal à
      revenus.heures_supplémentaires_et_rtt_exonérées
  définition exonérations_81_quater sous condition
    année_revenus >= 2022
  conséquence égal à
    plafond de assiette_exonérations_81_quater, 7500€
```

Before `égal à` there should be a 2-spaces indent instead of 4 (same behavior as `sous condition ... conséquence`)

Also, in 

```
  définition imputation_déficit_sur_revenu_quotientés_non_professionnels_locations_meublées.solde_catégoriel_à_imputer égal à
    solde_net_global_non_professionnel_locations_meublées état agrégation
```

The formatter should let me split the line before `égal à` or after `égal à`.

## State 

```
  définition imputation_aux_déficits_les_plus_anciens.revenu_déclaré égal à
    solde_net_global_non_professionnel_hors_locations_meublées état imputation_déficit_revenus_quotient
``` 

The formatter should let me split the line `solde_net_global_non_professionnel_hors_locations_meublées état imputation_déficit_revenus_quotient`.

**Comment by denismerigoux** [comment]
I want the following indentation:

```
champ d'application TraitementsSalairesDéclarant:
  définition assiette_exonérations_81_quater
    état art_81_quater
  égal à
      revenus.heures_supplémentaires_et_rtt_exonérées
```

**Comment by vincent-botbol** [comment]
I understood that however my question was referring to "sous condition ... conséquence".

**Comment by denismerigoux** [comment]
The following indentation :  

```
  définition exonérations_81_quater sous condition
    année_revenus >= 2022
  conséquence égal à
    plafond de assiette_exonérations_81_quater, 7500€
```
Is good for me and I don't want it changed :) Does that answer your question?

**Comment by vincent-botbol** [comment]
Indeed, thanks for the clarification
