### ISSUE TITLE
The compiler does not perform keyword avoidance when going to OCaml

### ISSUE THREAD

**Issue by msprotz** [CatalaLang/catala#85]
For instance:

```
(** This file has been generated by the Catala compiler, do not edit! *)

open Runtime

[@@@ocaml.warning "-26-27"]

type period = {
  begin: date;
  end: date;
}
```

note how `begin` and `end` are both OCaml keywords.

**Comment by denismerigoux** [comment]
Indeed, such keyword avoidance should be added when generating struct, enum, fields and var names here:

https://github.com/CatalaLang/catala/blob/611ef23fd1d15b8d29c234451fe0db06a79ecfa7/src/catala/lcalc/to_ocaml.ml#L128-L175
