### ISSUE TITLE
Feature request: exclusive-or operator

### ISSUE THREAD

**Issue by msprotz** [CatalaLang/catala#87]
Looking at https://sammade.github.io/aloha-io/title-17/chapter-286/section-286-136/ it appears that an exclusive or is required for the final paragraph (c). Sounds like it would a worthwhile addition to Catala.

**Comment by EmileRolley** [comment]
Wouldn't it be possible to use `!=` instead ?

**Comment by denismerigoux** [comment]
Technically yes but we want a `xor` for readability.

**Comment by denismerigoux** [comment]
Fixed by #93.
