### ISSUE TITLE
Change dates to ISO format

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#90]
## The problem

Right now, date literals are of the form `|01/01/2021|` in Catala. However, this format is confusing because Americans use the `MM/DD/YYYY` format instead of the logical `DD/MM/YYYY` format.

To remove this source of confusion, we should adopt the ISO format and write `|YYYY-MM-DD|`.

## How to implement the solution

This is the code responsible for date literal parsing:

https://github.com/CatalaLang/catala/blob/83ac8771169384bc5879862684525f3a86e0182d/src/catala/surface/parser.mly#L187-L193

It should be tweaked to implement the ISO format separated by dashes instead of `DIV`.

**Comment by EmileRolley** [comment]
I'm on it !

**Comment by EmileRolley** [comment]
This issue can be closed.
