### ISSUE TITLE
Bug in the Makefile

### ISSUE THREAD

**Issue by EmileRolley** [CatalaLang/catala#94]
Currently, an error occurs when trying to execute `make tests` just after a `make clean`:
[](url)
![Screenshot from 2021-03-16 18-17-53](https://user-images.githubusercontent.com/44124798/111356248-787c0500-8688-11eb-8d32-071a7f6dcfb8.png)

**Comment by denismerigoux** [comment]
These need to be silenced:

https://github.com/CatalaLang/catala/blob/fd1f72a313c94595e7718993c23329cb25b3fe93/src/catala/surface/dune#L19-L32

**Comment by denismerigoux** [comment]
Fixed, `parser.messages` needed to be updated.
