### ISSUE TITLE
No default target in Makefile

### ISSUE THREAD

**Issue by msprotz** [CatalaLang/catala#95]
```
jonathan@absinthe:~/Code/catala/examples/us_tax_code (master) $ make
latexmk -f -C us_tax_code.tex
Latexmk: This is Latexmk, John Collins, 26 Dec. 2019, version: 4.67.
Latexmk: Could not find file 'us_tax_code.tex'
rm -rf us_tax_code.tex \
		us_tax_code.d \
		_minted-us_tax_code \
		us_tax_code.html
```

This is because GNU make picks the first non-pattern rule to be the default target, in this case, the `clean` target. I suggest adding an `all` target at the beginning, and pick a suitable default; alternatively, the `all` target could print a help message with a few suggested targets.

**Comment by denismerigoux** [comment]
Good suggestion, will do. I had done that for the top-level Makefile but not for the examples-level Makefile.
