### ISSUE TITLE
Missing duration division operator

### ISSUE THREAD

**Issue by msprotz** [CatalaLang/catala#98]
For the latest work on Section 121, there is a notion of a ratio of days of nonqualified use over days of ownership.

It would be convenient to have an operator `/^: duration -> duration -> decimal`

**Comment by denismerigoux** [comment]
Indeed, it makes sense. However, this operator will raise runtime errors if it tries to divide durations of different units. For instance, dividing a number of days by a number of months, etc.

**Comment by denismerigoux** [comment]
Changes should be similar to #87
