### ISSUE TITLE
Syntax regression

### ISSUE THREAD

**Issue by msprotz** [CatalaLang/catala#99]
In the old syntax, the following was accepted:

```
@§286-136 Penalty@
 
/*
 scope Penalty286_83_135:
 
   rule fine_ok under condition min_fine <=$ fine and fine <=$ max_fine
```

but with the new syntax, it seems to be rejected:

```
## §286-136 Penalty

```catala
scope Penalty286_83_135:
```

with error:

```
[ERROR] Syntax error at token "```catala"
[ERROR] Message: expected an article title, another heading or some text
[ERROR] 
[ERROR] Error token:
[ERROR]   --> Title17-MotorAndOtherVehicles.catala_en
[ERROR]    | 
[ERROR] 58 | ```catala
[ERROR]    | ^^^^^^^^^
[ERROR]    + 
[ERROR] 
[ERROR] Last good token:
[ERROR]   --> Title17-MotorAndOtherVehicles.catala_en
[ERROR]    | 
[ERROR] 56 | ## §286-136 Penalty
[ERROR]    | ^^^^^^^^^^^^^^^^^^^
[ERROR] 57 | 
[ERROR]    | 
[ERROR] 58 | ```catala
[ERROR]    | ^
[ERROR]    + 
make: *** [Title17-MotorAndOtherVehicles.run] Error 1
```

**Comment by msprotz** [comment]
More precisely, there seems to be an implicit syntax invariant that only articles may appear under a heading; is that correct?

**Comment by EmileRolley** [comment]
> In the old syntax, the following was accepted:
> 
> ```
> @§286-136 Penalty@
>  
> /*
>  scope Penalty286_83_135:
>  
>    rule fine_ok under condition min_fine <=$ fine and fine <=$ max_fine
> ```
> 
> but with the new syntax, it seems to be rejected:
> 
> ```
> ## §286-136 Penalty
> 
> ```catala
> scope Penalty286_83_135:
> ```
> 
> with error:
> 
> ```
> [ERROR] Syntax error at token "```catala"
> [ERROR] Message: expected an article title, another heading or some text
> [ERROR] 
> [ERROR] Error token:
> [ERROR]   --> Title17-MotorAndOtherVehicles.catala_en
> [ERROR]    | 
> [ERROR] 58 | ```catala
> [ERROR]    | ^^^^^^^^^
> [ERROR]    + 
> [ERROR] 
> [ERROR] Last good token:
> [ERROR]   --> Title17-MotorAndOtherVehicles.catala_en
> [ERROR]    | 
> [ERROR] 56 | ## §286-136 Penalty
> [ERROR]    | ^^^^^^^^^^^^^^^^^^^
> [ERROR] 57 | 
> [ERROR]    | 
> [ERROR] 58 | ```catala
> [ERROR]    | ^
> [ERROR]    + 
> make: *** [Title17-MotorAndOtherVehicles.run] Error 1
> ```

With the new syntax law articles are distinguished from law headings with `[...]`. Consequently, I think you try:

```markdown
## [§286-136 Penalty]

```catala
....
```

**Comment by msprotz** [comment]
yes, that worked but I don't understand why there is a syntax restriction on something that should be purely cosmetic, right? in the end, does the article/heading distinction carry any semantic meaning? if not, why enforce strong syntax invariants?

**Comment by EmileRolley** [comment]
I am not sure but I think that catala code block should be a child of a law article.

**Comment by msprotz** [comment]
my mental model was that, this being literate programming, it would just be a series of markdown or catala chunks, and that the markdown would carry no semantic meaning; apparently there's a tree-like structure that's being built underneath; what do you use the tree for?

**Comment by msprotz** [comment]
I should also mention that your suggestion gave me:

```
jonathan@absinthe:~/Code/catala/examples/hawaii_lfo (master) $ SCOPE=Penalty286_83_135 make Title17-MotorAndOtherVehicles.run
File "parser.messages", line 1855, characters 0-137:
Error: this sentence does not end with a syntax error, as it should:
a syntax error occurs before the last token is reached.
File "parser.messages", line 1867, characters 0-125:
Error: this sentence does not end with a syntax error, as it should:
a syntax error occurs before the last token is reached.
File "parser.messages", line 1879, characters 0-121:
Error: this sentence does not end with a syntax error, as it should:
a syntax error occurs before the last token is reached.
File "parser.messages", line 1891, characters 0-109:
Error: this sentence does not end with a syntax error, as it should:
a syntax error occurs before the last token is reached.
Read 152 sample input sentences and 152 error messages.
make: *** [Title17-MotorAndOtherVehicles.run] Error 1
```

and that I had to remove the § sign. Not sure if this should be the same issue or not...

**Comment by EmileRolley** [comment]
I looked at the `surface/ast.ml` and I found a confirmation of my hypothesis  :

```ocaml
type law_article_item = LawText of (string[@opaque]) | CodeBlock of code_block * source_repr
...
type law_structure =
  | LawInclude of law_include
  | LawHeading of law_heading * law_structure list
  | LawArticle of law_article * law_article_item list
  ...
```

**Comment by EmileRolley** [comment]
> my mental model was that, this being literate programming, it would just be a series of markdown or catala chunks, and that the markdown would carry no semantic meaning; apparently there's a tree-like structure that's being built underneath; what do you use the tree for?

For design choices you need to ask directly to @denismerigoux I think...

**Comment by denismerigoux** [comment]
The correct new syntax is 
```## [§286-136 Penalty]

```catala
scope Penalty286_83_135:
```

**Comment by denismerigoux** [comment]
Notice the brackets around the heading title, which marks an "article", the same way single brackets do.

The tree structure is used for #29, the `Pos.t` are enhanced with the path inside the legislative structure tree, which helps display logging position and error message with the position inside the structure of the legislative text as well as the position in terms of line of code number.

**Comment by denismerigoux** [comment]
The only hard requirement, which you have hit with your example, is that every piece of Catala code fits inside an `## [Article]` block. This promotes the idea that every blob of Catala code should be justified by a legislative article.

**Comment by denismerigoux** [comment]
> jonathan@absinthe:~/Code/catala/examples/hawaii_lfo (master) $ SCOPE=Penalty286_83_135 make Title17-MotorAndOtherVehicles.run
> File "parser.messages", line 1855, characters 0-137:
> Error: this sentence does not end with a syntax error, as it should:
> a syntax error occurs before the last token is reached.
> File "parser.messages", line 1867, characters 0-125:
> Error: this sentence does not end with a syntax error, as it should:
> a syntax error occurs before the last token is reached.
> File "parser.messages", line 1879, characters 0-121:
> Error: this sentence does not end with a syntax error, as it should:
> a syntax error occurs before the last token is reached.
> File "parser.messages", line 1891, characters 0-109:
> Error: this sentence does not end with a syntax error, as it should:
> a syntax error occurs before the last token is reached.
> Read 152 sample input sentences and 152 error messages.
> make: *** [Title17-MotorAndOtherVehicles.run] Error 1

That's definitely weird, looks like a parser/lexer failure cause by `§` ? Will investigate.

**Comment by denismerigoux** [comment]
The weird failure has been fixed, will close.
